<h1><center>IST 597 Foundations of Deep Learning</center></h1>

---

<h2><center>Introduction to Numpy</center><h2>
<h3><center>Neisarg Dave</center><h3>

In [ ]:
import numpy as np

In [ ]:
# define a vector
x = np.array([1, 2, 3])

In [ ]:
# define a matrix
W = np.array([[3, 2, 4], [2, 4, 6], [2,3,5]])

In [ ]:
print(x)

[1 2 3]


In [ ]:
print(W)

[[3 2 4]
 [2 4 6]
 [2 3 5]]


In [ ]:
# create a tensor by randomly sampling items

y = np.random.normal(0, 0.1, [3,4,5])

In [ ]:
print(y)

[[[ 0.03732673  0.01910664 -0.0477772   0.01092149 -0.13727826]
  [-0.10904146  0.08789071  0.03527119  0.02249733  0.01392489]
  [-0.01673353 -0.05173891  0.03604465  0.08247068  0.15900733]
  [-0.01869403  0.11859939 -0.17065472 -0.00971685 -0.12654637]]

 [[-0.22836514  0.15077142 -0.04916937  0.09836347 -0.00060319]
  [-0.00430319 -0.05227154  0.00592959 -0.21145796 -0.06713323]
  [ 0.030606    0.13587376 -0.07285492  0.1899199  -0.0908815 ]
  [ 0.00654115 -0.02034705 -0.00078861  0.01228811 -0.07431388]]

 [[ 0.1734298  -0.08835432 -0.0161402  -0.17751684  0.05741935]
  [ 0.05563815 -0.05588137 -0.09211308  0.01369716 -0.11301392]
  [-0.03035558  0.16213583 -0.16765074 -0.04628646  0.04527912]
  [-0.00102507  0.03017409 -0.00832414 -0.00272386  0.00614011]]]


In [ ]:
# Indexing

print(y[0])

[[ 0.03732673  0.01910664 -0.0477772   0.01092149 -0.13727826]
 [-0.10904146  0.08789071  0.03527119  0.02249733  0.01392489]
 [-0.01673353 -0.05173891  0.03604465  0.08247068  0.15900733]
 [-0.01869403  0.11859939 -0.17065472 -0.00971685 -0.12654637]]


In [ ]:
print(y[0, 1])

[-0.10904146  0.08789071  0.03527119  0.02249733  0.01392489]


In [ ]:
print(y[1, 1:-1])

[[-0.06403809 -0.02710169  0.10787146 -0.06506309 -0.1381459 ]
 [ 0.01675156 -0.09052515  0.06529768  0.08843727  0.06415556]]


In [ ]:
# create a list of 10 vectors

a = [np.random.randint(0, 9, size=[10]) for i in range(10)]
print(a)


[array([1, 3, 2, 2, 8, 8, 4, 5, 2, 3]), array([7, 0, 8, 1, 0, 4, 1, 6, 7, 5]), array([7, 5, 7, 0, 7, 6, 3, 8, 3, 5]), array([4, 6, 2, 2, 0, 7, 8, 3, 5, 0]), array([8, 0, 4, 3, 3, 1, 8, 0, 6, 4]), array([0, 1, 7, 4, 3, 4, 8, 4, 5, 8]), array([0, 1, 6, 1, 0, 6, 5, 0, 4, 1]), array([0, 5, 2, 0, 5, 6, 1, 1, 7, 4]), array([5, 3, 2, 0, 0, 6, 0, 0, 8, 3]), array([8, 7, 6, 4, 1, 6, 0, 7, 8, 0])]


In [ ]:
print(len(a), a[0].shape)

10 (10,)


In [ ]:
# stack vectors in list
stacked_0 = np.stack(a, axis=0)
print(stacked_0)

[[1 3 2 2 8 8 4 5 2 3]
 [7 0 8 1 0 4 1 6 7 5]
 [7 5 7 0 7 6 3 8 3 5]
 [4 6 2 2 0 7 8 3 5 0]
 [8 0 4 3 3 1 8 0 6 4]
 [0 1 7 4 3 4 8 4 5 8]
 [0 1 6 1 0 6 5 0 4 1]
 [0 5 2 0 5 6 1 1 7 4]
 [5 3 2 0 0 6 0 0 8 3]
 [8 7 6 4 1 6 0 7 8 0]]


In [ ]:
stacked_1 = np.stack(a, axis=1)
print(stacked_1)

[[1 7 7 4 8 0 0 0 5 8]
 [3 0 5 6 0 1 1 5 3 7]
 [2 8 7 2 4 7 6 2 2 6]
 [2 1 0 2 3 4 1 0 0 4]
 [8 0 7 0 3 3 0 5 0 1]
 [8 4 6 7 1 4 6 6 6 6]
 [4 1 3 8 8 8 5 1 0 0]
 [5 6 8 3 0 4 0 1 0 7]
 [2 7 3 5 6 5 4 7 8 8]
 [3 5 5 0 4 8 1 4 3 0]]


In [ ]:
print(stacked_1.transpose())

[[1 3 2 2 8 8 4 5 2 3]
 [7 0 8 1 0 4 1 6 7 5]
 [7 5 7 0 7 6 3 8 3 5]
 [4 6 2 2 0 7 8 3 5 0]
 [8 0 4 3 3 1 8 0 6 4]
 [0 1 7 4 3 4 8 4 5 8]
 [0 1 6 1 0 6 5 0 4 1]
 [0 5 2 0 5 6 1 1 7 4]
 [5 3 2 0 0 6 0 0 8 3]
 [8 7 6 4 1 6 0 7 8 0]]


In [ ]:
stacked_1.transpose() == stacked_0

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [ ]:
x = np.arange(10)
W = np.random.normal(0, 0.1, size = [6, 10])
print(x)
print(x.shape, W.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,) (6, 10)


In [ ]:
# matrix multiplication
y = np.matmul(W, x)
print(y.shape)
print(y)

(6,)
[-6.58710987 -0.61427265 -0.75192251 -0.45701643 -2.85868583  2.48842246]


In [ ]:
# Hadamard Product : Element Wise Product
z = W*x
print(z.shape)
print(z)

(6, 10)
[[ 0.00000000e+00  3.32846803e-02  5.74861039e-02 -5.37780533e-01
  -2.47698946e-01 -1.06166759e+00 -1.14196265e+00  6.64290854e-01
  -2.56941836e+00 -1.78364344e+00]
 [ 0.00000000e+00  8.33086025e-02 -4.38063170e-02 -5.52087154e-01
   5.09782839e-01  4.69463298e-01  8.21797457e-01  4.33027777e-02
  -1.44511652e-01 -1.80152251e+00]
 [ 0.00000000e+00  9.35202647e-02  3.93598024e-02 -3.52738590e-01
   5.14086354e-01 -3.99302660e-01  6.74784313e-01 -1.42180674e+00
   6.48800584e-01 -5.48625832e-01]
 [-0.00000000e+00  3.61280520e-02 -1.15617142e-02  4.53197496e-01
  -1.41621680e-01  1.41889336e-01 -5.90621898e-02 -2.67925291e-01
   4.66280279e-01 -1.07434072e+00]
 [ 0.00000000e+00  4.24481286e-02  1.75249154e-01 -6.77933386e-04
  -7.51481090e-01  5.46906713e-01 -9.65568795e-01 -4.13397547e-01
  -1.45235697e+00 -3.98074906e-02]
 [ 0.00000000e+00  6.59696417e-02  4.11977470e-01 -3.11246711e-01
  -1.24914788e-02  5.15178992e-03  6.39853301e-01  8.09702265e-01
   3.95283565e-01  4.8422

In [ ]:
print(z[:, 1])

[0.03328468 0.0833086  0.09352026 0.03612805 0.04244813 0.06596964]


In [ ]:
print(z[:, 1])

[-0.01440825 -0.06144244  0.12316328 -0.05065183 -0.04300129  0.03232346]


In [ ]:
print(z[:, 1] == W[:, 1])

[ True  True  True  True  True  True]
